name: pulsar-grpc mvn build check and ut

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: License check
        run: mvn -B license:check

      - name: Build with Maven skipTests
        run: mvn -B clean install -DskipTests

      - name: Style check
        run: mvn -B checkstyle:check

      - name: Spotbugs check
        run: mvn -B spotbugs:check

      - name: test after build
        run: mvn -B test -DfailIfNoTests=false
